from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth as a module
module rna_seq_kallisto_sleuth:
    snakefile: 
        github("snakemake-workflows/rna-seq-kallisto-sleuth", path="workflow/Snakefile", tag="v2.3.2")
    config:
        config


# use all rules from https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth
use rule * from rna_seq_kallisto_sleuth
